// $Header:   D:/databases/VMdb/archives/DCX/DCP/DCP Application/CyGOS/stdlib/stdlib.h_v   1.0   29 Oct 2010 10:39:48   ygupta  $
//
// Copyright (c) Cyber Group, Inc 2007
// This program is the property of Cyber Group Inc
// Copying of this software is expressly forbidden, without the prior written
// consent of Cyber Group Inc
//
// This file is part of CyGOS-3.
//
// This module declares stdlib.h functions so that we will not have to use
// libraries provided by the compiler. Their overhead is unknown and may
// interfere with our system design. ASM generated by the compiler is good
// enough so we don't need to go bit-twiddling with these functions.

#ifndef STDLIB_H_
#define STDLIB_H_

#include "ArchDefs.h"

#define NULL (0)

extern "C"
{

void * calloc(size_t num, size_t size);
void * malloc(size_t size);
void free(void * ptr);

int atoi(const char * string);
int xtoi(const char * hexNumber);
int otoi(const char * hexNumber);

}

#endif
