// $Header:   D:/databases/VMdb/archives/DCX/RackMount/DCP/CyGOS/stdlib/string.h_v   1.0   18 Aug 2014 09:16:50   amaurya  $
//
// Copyright (c) Cyber Group, Inc 2007
// This program is the property of Cyber Group Inc
// Copying of this software is expressly forbidden, without the prior written
// consent of Cyber Group Inc
//
// This file is part of CyGOS-3.
//
// This module declares string.h functions so that we will not have to use
// libraries provided by the compiler. Their overhead is unknown and may
// interfere with our system design. ASM generated by the compiler is good
// enough so we don't need to go bit-twiddling with these functions.

#ifndef STRING_H_
#define STRING_H_

extern "C"
{
void * memcpy(void * dst, const void * src, int len);
void * memset(void *s, int c, unsigned n);
int memcmp(const void * p1, const void * p2, int len);
void *memmove(void * dst, const void * src, int n);
void *memchr(const void * s, int c, int n);

int strlen(const char *str);
char * strcat(char * dst, const char * src);
char * strcpy(char * dst, const char * src);
int strcmp(const char * s1, const char * s2);
int strncmp(const char * s1, const char * s2, int n);
int stricmp(const char * s1, const char * s2);
int strnicmp(const char * s1, const char * s2, int n);
char * strdup(const char *str);
char * strchr(const char *str, int ch);
char * strupr(char *str);
char * strrchr(const char *str, int ch);
char * strstr(const char * string, const char * search);
char * strncpy(char* dst,const char * src,int n);
char * strlower(char *str);
}

#endif
