# $Header: /CyGOS3/BransonCyGOSIndia/Devices/Makefile,v 1.1 2010/09/29 14:10:38 noor Exp $
#
# Copyright (c) Cyber Group, Inc 2008
# This program is the property of Cyber Group Inc
# Copying of this software is expressly forbidden, without the prior written
# consent of Cyber Group Inc
#
# This file is part of CyGOS-3.
#
# This is the Devices directory make file.
#
# This makefile should be included from the board-specific Makefile.

OSCPP = OS_Custom.cpp

# ADV212.cpp ADV212Test.cpp ADV212Firmware.cpp ADV212Decoder.cpp \
# ADV212Encoder.cpp

# This is a relative path to device files from the BSP folder.
OSDIR = ../../../../CifxToolkit/OSAbstraction

OSOBJ = $(addprefix $(OBJ_DIR)/OS_, $(OSCPP:.cpp=_cpp.o))

INC += $(OSDIR)

OBJ += $(OSOBJ)

$(OBJ_DIR)/OS_%_cpp.o : $(OSDIR)/%.cpp $(wildcard $(addsuffix /*.h,$(INC)))
	$(CC) $(CCOPT) -o $@ $<
