/*
$Header:   D:/databases/VMdb/archives/DCX/Weld Controller/Application/SCAN.H_v   1.1   05 Jul 2012 04:47:00   ygupta  $
*/
/****************************************************************************/
/*                                                                          */
/*                                                                          */
/*      Copyright (c) Branson Ultrasonics Corporation, 1995,96, 2009        */
/*     This program is the property of Branson Ultrasonics Corporation      */
/*   Copying of this software is expressly forbidden, without the prior     */
/*   written consent of Branson Ultrasonics Corporation.                    */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*************************                         **************************/
/*****************************************************************************
$Log:   D:/databases/VMdb/archives/DCX/Weld Controller/Application/SCAN.H_v  $
 * 
 *    Rev 1.1   05 Jul 2012 04:47:00   ygupta
 * Cleanup after review summary on database and BSP.
 * 
 *    Rev 1.0   02 Jul 2012 12:46:46   ygupta
 * Initial revision.

******************************************************************************/
#ifndef SCAN_H_
#define SCAN_H_



#endif /* SCAN_H_ */
