# $Header: /CyGOS3/BransonCyGOSIndia/Devices/Makefile,v 1.1 2010/09/29 14:10:38 noor Exp $
#
# Copyright (c) Cyber Group, Inc 2008
# This program is the property of Cyber Group Inc
# Copying of this software is expressly forbidden, without the prior written
# consent of Cyber Group Inc
#
# This file is part of CyGOS-3.
#
# This is the Devices directory make file.
#
# This makefile should be included from the board-specific Makefile.

SRCCPP = cifXDownload.cpp cifXEndianess.cpp cifXFunctions.cpp cifXInit.cpp cifXHWFunctions.cpp cifXInterrupt.cpp \
md5.cpp

# ADV212.cpp ADV212Test.cpp ADV212Firmware.cpp ADV212Decoder.cpp \
# ADV212Encoder.cpp

# This is a relative path to device files from the BSP folder.
SRCDIR = ../../../../CifxToolkit/Source

SRCOBJ = $(addprefix $(OBJ_DIR)/SRC_, $(SRCCPP:.cpp=_cpp.o))

INC += $(SRCDIR)

OBJ += $(SRCOBJ)

$(OBJ_DIR)/SRC_%_cpp.o : $(SRCDIR)/%.cpp $(wildcard $(addsuffix /*.h,$(INC)))
	$(CC) $(CCOPT) -o $@ $<
