# $Header: /CyGOS3/BransonCyGOSIndia/Devices/Makefile,v 1.1 2010/09/29 14:10:38 noor Exp $
#
# Copyright (c) Cyber Group, Inc 2008
# This program is the property of Cyber Group Inc
# Copying of this software is expressly forbidden, without the prior written
# consent of Cyber Group Inc
#
# This file is part of CyGOS-3.
#
# This is the Devices directory make file.
#
# This makefile should be included from the board-specific Makefile.

HWCPP = DPMInterface.cpp

# ADV212.cpp ADV212Test.cpp ADV212Firmware.cpp ADV212Decoder.cpp \
# ADV212Encoder.cpp

# This is a relative path to device files from the BSP folder.
HWDIR = ../../../../CifxToolkit/HWInterface

HWOBJ = $(addprefix $(OBJ_DIR)/HW_, $(HWCPP:.cpp=_cpp.o))

INC += $(HWDIR)

OBJ += $(HWOBJ)

$(OBJ_DIR)/HW_%_cpp.o : $(HWDIR)/%.cpp $(wildcard $(addsuffix /*.h,$(INC)))
	$(CC) $(CCOPT) -o $@ $<
